### ISSUE TITLE
Add package:gpg for later use by tlmgr

### ISSUE THREAD

**Issue by iiegn** [thorsten-winkler/docker-texlive#1]
later, `tlmgr` downloads packages but can't verify them without `gpg`:
```
tlmgr: package repository http://ctan.mirror.garr.it/mirrors/CTAN/systems/texlive/tlnet (not verified: gpg unavailable)
```

...adding `gpg` to the `ENV PERSISTENT_DEPS` solves this.

https://github.com/thorsten-winkler/docker-texlive/blob/a5af69061f4b2c17e1715a88bce06499930dd8ea/2019/Dockerfile.minimal#L13

**Comment by thowdev** [comment]
Sry for not replying...I only saw it yesterday when I wanted to update the images to TL2020.
I added the package `gpg` now and tried it out:

```
# tlmgr update --list
tlmgr: package repository http://ftp.math.purdue.edu/mirrors/ctan.org/systems/texlive/tlnet (verified)
tlmgr: would save backups to /usr/local/texlive/2019/tlpkg/backups
tlmgr: no updates available
```

Due to the update all `2019`-images were built again.
This update seems to cause that all `2019`-images using TL 2020 packages now. Therefore I will delete the `2019`-images from dockerhub and you should use the `2020`-images which of course have the `gpg` package installed
